In [1]:
# 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [7]:
# 2. Print the numpy version and the configuration
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/build-env-77v4s

In [12]:
# 3. Create a null vector of size 10
a = np.full(10, np.nan)
b = np.zeros(10)
print(a, b)

[nan nan nan nan nan nan nan nan nan nan] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
# 4. How to find the memory size of any array
a.nbytes

80

In [16]:
# 6.Create a null vector of size 10 but the fifth value which is 1
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
# 7. Create a vector with values ranging from 10 to 49
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
# 8. Reverse a vector (first element becomes last) 
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [23]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4]),)

In [28]:
# 11. Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# 12. Create a 3x3x3 array with random values
import random
np.random.random(27).reshape(3,3,3)

array([[[0.5203846 , 0.56059277, 0.21455966],
        [0.04760619, 0.9411604 , 0.25659543],
        [0.21399525, 0.35716227, 0.36785836]],

       [[0.24716982, 0.85218244, 0.93638266],
        [0.22227858, 0.63122928, 0.03343906],
        [0.72090491, 0.0790371 , 0.41949935]],

       [[0.05015808, 0.65079998, 0.52086832],
        [0.34146003, 0.38069297, 0.67853244],
        [0.35069565, 0.98279982, 0.2898467 ]]])

In [40]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
matrix = np.random.random((10,10))
matrix.min(), matrix.max()

(np.float64(0.005302964587576953), np.float64(0.994993709045562))

In [44]:
# 14. Create a random vector of size 30 and find the mean value
rand_vect = np.random.random(30)
np.mean(rand_vect)

np.float64(0.5059729414878816)

In [59]:
# 15. Create a 2d array with 1 on the border and 0 inside
one = np.ones((8,5))
row = one.shape[0]
col = one.shape[1]
one[1:row-1, 1:col-1] = 0
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
# 16. How to add a border (filled with 0's) around an existing array?
some_array = np.ones((10,10))*5
zeros = np.zeros((some_array.shape[0]+2, some_array.shape[1]+2))
zeros[1:-1, 1:-1] = some_array
zeros

#16.1
np.pad(some_array, pad_width=1,mode="constant", constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [80]:
### 17. What is the result of the following expression? (★☆☆)

print(0 * np.nan, #nan
np.nan == np.nan, #false
np.inf > np.nan, #false
np.nan - np.nan, #nan
np.nan in set([np.nan]), #True
0.3 == 3 * 0.1) #false

nan False False nan True False


In [87]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(np.arange(1,5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
pattern = np.zeros((8,8))
pattern[0::2,0:2] = 1
pattern[1:,1::2] = 1
pattern

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
matrix = np.random.random((6,7,8))
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

In [101]:
# 21. Create a checkerboard 8x8 matrix using the tile function

pattern = np.array([[0,1], [1,0]])

np.tile(pattern, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [106]:
# 22. Normalize a 5x5 random matrix
tab = np.arange(1,10).reshape(3,3)
(tab - np.mean(tab))/np.std(tab)

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [114]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

rgba = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
picture = np.zeros((10,10), dtype=rgba)
picture[0,0]["a"] = 200

In [119]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
a @ b
np.matmul(a,b)


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [124]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
nums = np.arange(20)
nums[(nums> 3) & (nums < 8)] *= -1
nums

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
## 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1)) # here sum is -1 + 0 + 1 + 2 + 3 + 4 + 5, python sum
from numpy import *
print(sum(range(5),-1)) # here -1 is axis, so we just sum all elements, numpy sum

In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal?
Z = np.array([1,3,4])
Z**Z # ok a ^ a
2 << Z >> 2 # 2 << Z  2*2^z,   Z>> 2.  2*2^z  / 2^2.   bit manipualtion
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [139]:
# 28. What are the result of the following expressions? (★☆☆)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/3688598899.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/3688598899.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/3688598899.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [148]:
# 29. How to round away from zero a float array ?
a = np.arange(-5.5,5.5,1)
np.where(a> 0, np.ceil(a), np.floor(a))

array([-6., -5., -4., -3., -2., -1.,  1.,  2.,  3.,  4.,  5.])

In [150]:
# 30. How to find common values between two arrays?
a = np.arange(10)
b = np.arange(5,15)
np.intersect1d(a,b)

array([5, 6, 7, 8, 9])

In [151]:
# 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/1487511943.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [153]:
# 33. How to get the dates of yesterday, today and tomorrow?
np.datetime64('today') + np.timedelta64(1)

np.datetime64('2026-03-21')

In [161]:
# 34. How to get all the dates corresponding to the month of July 2016?
np.arange('2016-07', '2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')