In [2]:
# 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [7]:
# 2. Print the numpy version and the configuration
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/nb/lcynqsvj2fvf0gqkbj2_nxwh0000gn/T/build-env-77v4s

In [12]:
# 3. Create a null vector of size 10
a = np.full(10, np.nan)
b = np.zeros(10)
print(a, b)

[nan nan nan nan nan nan nan nan nan nan] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
# 4. How to find the memory size of any array
a.nbytes

80

In [16]:
# 6.Create a null vector of size 10 but the fifth value which is 1
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
# 7. Create a vector with values ranging from 10 to 49
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [20]:
# 8. Reverse a vector (first element becomes last) 
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [23]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
a = np.array([1,2,0,0,4,0])
a.nonzero()

(array([0, 1, 4]),)

In [28]:
# 11. Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# 12. Create a 3x3x3 array with random values
import random
np.random.random(27).reshape(3,3,3)

array([[[0.5203846 , 0.56059277, 0.21455966],
        [0.04760619, 0.9411604 , 0.25659543],
        [0.21399525, 0.35716227, 0.36785836]],

       [[0.24716982, 0.85218244, 0.93638266],
        [0.22227858, 0.63122928, 0.03343906],
        [0.72090491, 0.0790371 , 0.41949935]],

       [[0.05015808, 0.65079998, 0.52086832],
        [0.34146003, 0.38069297, 0.67853244],
        [0.35069565, 0.98279982, 0.2898467 ]]])

In [40]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
matrix = np.random.random((10,10))
matrix.min(), matrix.max()

(np.float64(0.005302964587576953), np.float64(0.994993709045562))

In [44]:
# 14. Create a random vector of size 30 and find the mean value
rand_vect = np.random.random(30)
np.mean(rand_vect)

np.float64(0.5059729414878816)

In [59]:
# 15. Create a 2d array with 1 on the border and 0 inside
one = np.ones((8,5))
row = one.shape[0]
col = one.shape[1]
one[1:row-1, 1:col-1] = 0
one

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
# 16. How to add a border (filled with 0's) around an existing array?
some_array = np.ones((10,10))*5
zeros = np.zeros((some_array.shape[0]+2, some_array.shape[1]+2))
zeros[1:-1, 1:-1] = some_array
zeros

#16.1
np.pad(some_array, pad_width=1,mode="constant", constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [80]:
### 17. What is the result of the following expression? (★☆☆)

print(0 * np.nan, #nan
np.nan == np.nan, #false
np.inf > np.nan, #false
np.nan - np.nan, #nan
np.nan in set([np.nan]), #True
0.3 == 3 * 0.1) #false

nan False False nan True False


In [87]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(np.arange(1,5), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
pattern = np.zeros((8,8))
pattern[0::2,0:2] = 1
pattern[1:,1::2] = 1
pattern

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
matrix = np.random.random((6,7,8))
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

In [101]:
# 21. Create a checkerboard 8x8 matrix using the tile function

pattern = np.array([[0,1], [1,0]])

np.tile(pattern, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [106]:
# 22. Normalize a 5x5 random matrix
tab = np.arange(1,10).reshape(3,3)
(tab - np.mean(tab))/np.std(tab)

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [114]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

rgba = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
picture = np.zeros((10,10), dtype=rgba)
picture[0,0]["a"] = 200

In [119]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
a @ b
np.matmul(a,b)


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [124]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
nums = np.arange(20)
nums[(nums> 3) & (nums < 8)] *= -1
nums

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
## 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1)) # here sum is -1 + 0 + 1 + 2 + 3 + 4 + 5, python sum
from numpy import *
print(sum(range(5),-1)) # here -1 is axis, so we just sum all elements, numpy sum

In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal?
Z = np.array([1,3,4])
Z**Z # ok a ^ a
2 << Z >> 2 # 2 << Z  2*2^z,   Z>> 2.  2*2^z  / 2^2.   bit manipualtion
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [139]:
# 28. What are the result of the following expressions? (★☆☆)
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/3688598899.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/3688598899.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/3688598899.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [148]:
# 29. How to round away from zero a float array ?
a = np.arange(-5.5,5.5,1)
np.where(a> 0, np.ceil(a), np.floor(a))

array([-6., -5., -4., -3., -2., -1.,  1.,  2.,  3.,  4.,  5.])

In [150]:
# 30. How to find common values between two arrays?
a = np.arange(10)
b = np.arange(5,15)
np.intersect1d(a,b)

array([5, 6, 7, 8, 9])

In [151]:
# 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_14763/1487511943.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [153]:
# 33. How to get the dates of yesterday, today and tomorrow?
np.datetime64('today') + np.timedelta64(1)

np.datetime64('2026-03-21')

In [161]:
# 34. How to get all the dates corresponding to the month of July 2016?
np.arange('2016-07', '2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [6]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
a = np.array([1.0,2,3])
b = np.array([4.0,5,6])

np.add(a,b,out=b)
np.divide(a,2.0,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
a

array([ -2.5,  -7. , -13.5])

In [28]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
import random
np.random.seed(20)
a = np.random.uniform(0,100,5)
np.floor(a)
a // 1
a.astype(int)
np.trunc(a)


array([58., 89., 89., 81.,  3.])

In [47]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
np.tile(np.arange(0,5),5).reshape(5,5)
np.tile(np.arange(0,5),(5,1))
res = np.zeros((5,5))
res += np.arange(0,5)
res

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [57]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generator(limit):
    n = 10
    while n <= limit:
        yield n**2
        n+= 1

np.fromiter(generator(20), dtype=int)

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [64]:
## 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
np.linspace(0,1,11,endpoint=False)[1:]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [69]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
vector = np.random.uniform(0,10,10)
vector.sort()
vector

array([1.56391719, 1.6162871 , 4.08643432, 5.82241123, 5.9813382 ,
       7.34300519, 7.78687904, 7.86071444, 8.03970568, 8.25823577])

In [73]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
a = np.array([1,2,3,4,5])
np.add.reduce(a)

np.int64(15)

In [81]:
#### 42. Consider two random arrays A and B, check if they are equal (★★☆)
a = np.random.random(10)
b = np.random.random(10)
a == b
print(a==b, np.equal(a,b), np.isclose(a,b), np.array_equal(a,b))

[False False False False False False False False False False] [False False False False False False False False False False] [False False False False False False False False False False] False


In [88]:
#### 43. Make an array immutable (read-only) (★★☆)
a = np.array([1,2,3])
a.flags.writeable = False
a

array([1, 2, 3])

In [91]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
cord = np.random.uniform(0,1,(10,2))
X = cord[:,0]
Y = cord[:,1]
T = np.arctan2(Y,X)
r = np.sqrt(X**2+Y**2)
print(T,r)

[1.21068114 1.41240733 1.03574546 0.27608555 1.53156143 0.68754775
 0.74132926 0.52295278 0.75718913 0.60384408] [1.02468117 0.96350239 0.93860972 0.65784673 0.94734572 1.15188095
 0.62196822 0.96867802 0.55377309 1.14979214]


In [95]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
vect = np.random.uniform(0,100,10)
vect[np.argmax(vect)] = 0
vect

array([26.32499628, 31.98365   , 95.79067356,  0.        , 63.64599555,
       75.29076184, 96.22445473, 82.50616911, 22.02412956, 23.81088492])

In [99]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
a = np.linspace(0,1,5)
np.vstack([a,a])


array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [111]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
matrix = np.zeros((5,5), [('x', float), ('y', float)])
matrix['x'], matrix['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
matrix

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [121]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
x = np.arange(1,6)
y = np.arange(6, 12)

1/np.subtract.outer(x,y)

array([[-0.2       , -0.16666667, -0.14285714, -0.125     , -0.11111111,
        -0.1       ],
       [-0.25      , -0.2       , -0.16666667, -0.14285714, -0.125     ,
        -0.11111111],
       [-0.33333333, -0.25      , -0.2       , -0.16666667, -0.14285714,
        -0.125     ],
       [-0.5       , -0.33333333, -0.25      , -0.2       , -0.16666667,
        -0.14285714],
       [-1.        , -0.5       , -0.33333333, -0.25      , -0.2       ,
        -0.16666667]])

In [132]:
#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

print(np.iinfo(np.int16), np.finfo(np.float32).min)


Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------
 -3.4028235e+38


In [135]:
#### 49. How to print all the values of an array? (★★☆)
np.set_printoptions(threshold=float("inf"))

print(np.ones((25,25)))


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [139]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
a = np.array([1,2,3,4,5,6])
value = 100

a[np.argmin(np.abs(a - value))]

np.int64(6)

In [171]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
a = np.zeros((5,5), [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])])
a["position"]['x'], a['position']['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
a["color"]["r"], a["color"]["g"], a["color"]["b"] = (50,100,150)
a

array([[((0.  , 0.  ), (50, 100, 150)), ((0.25, 0.  ), (50, 100, 150)),
        ((0.5 , 0.  ), (50, 100, 150)), ((0.75, 0.  ), (50, 100, 150)),
        ((1.  , 0.  ), (50, 100, 150))],
       [((0.  , 0.25), (50, 100, 150)), ((0.25, 0.25), (50, 100, 150)),
        ((0.5 , 0.25), (50, 100, 150)), ((0.75, 0.25), (50, 100, 150)),
        ((1.  , 0.25), (50, 100, 150))],
       [((0.  , 0.5 ), (50, 100, 150)), ((0.25, 0.5 ), (50, 100, 150)),
        ((0.5 , 0.5 ), (50, 100, 150)), ((0.75, 0.5 ), (50, 100, 150)),
        ((1.  , 0.5 ), (50, 100, 150))],
       [((0.  , 0.75), (50, 100, 150)), ((0.25, 0.75), (50, 100, 150)),
        ((0.5 , 0.75), (50, 100, 150)), ((0.75, 0.75), (50, 100, 150)),
        ((1.  , 0.75), (50, 100, 150))],
       [((0.  , 1.  ), (50, 100, 150)), ((0.25, 1.  ), (50, 100, 150)),
        ((0.5 , 1.  ), (50, 100, 150)), ((0.75, 1.  ), (50, 100, 150)),
        ((1.  , 1.  ), (50, 100, 150))]],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', 

In [ ]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

array = np.arange(1,201).reshape(100,2)

x,y = np.atleast_2d(array[:,0], array[:,1])
np.sqrt((x-x.T)**2+(y-y.T)**2)

array([[  0.        ,   2.82842712,   5.65685425,   8.48528137,
         11.3137085 ,  14.14213562,  16.97056275,  19.79898987,
         22.627417  ,  25.45584412,  28.28427125,  31.11269837,
         33.9411255 ,  36.76955262,  39.59797975,  42.42640687,
         45.254834  ,  48.08326112,  50.91168825,  53.74011537,
         56.56854249,  59.39696962,  62.22539674,  65.05382387,
         67.88225099,  70.71067812,  73.53910524,  76.36753237,
         79.19595949,  82.02438662,  84.85281374,  87.68124087,
         90.50966799,  93.33809512,  96.16652224,  98.99494937,
        101.82337649, 104.65180362, 107.48023074, 110.30865787,
        113.13708499, 115.96551211, 118.79393924, 121.62236636,
        124.45079349, 127.27922061, 130.10764774, 132.93607486,
        135.76450199, 138.59292911, 141.42135624, 144.24978336,
        147.07821049, 149.90663761, 152.73506474, 155.56349186,
        158.39191899, 161.22034611, 164.04877324, 166.87720036,
        169.70562748, 172.53405461, 175.

In [ ]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?
a = np.zeros(100, dtype=np.float32)
y = a.view(np.int32)
y[:] = a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [207]:
#### 54. How to read the following file? (★★☆)
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
txt = np.genfromtxt(s, delimiter=",", dtype = int, filling_values = -1)
txt

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

In [217]:
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

a = np.arange(0,100).reshape(10,10)

for index in np.ndindex(a.shape):
    print(index, a[index])

for index, value in np.ndenumerate(a):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(0, 5) 5
(0, 6) 6
(0, 7) 7
(0, 8) 8
(0, 9) 9
(1, 0) 10
(1, 1) 11
(1, 2) 12
(1, 3) 13
(1, 4) 14
(1, 5) 15
(1, 6) 16
(1, 7) 17
(1, 8) 18
(1, 9) 19
(2, 0) 20
(2, 1) 21
(2, 2) 22
(2, 3) 23
(2, 4) 24
(2, 5) 25
(2, 6) 26
(2, 7) 27
(2, 8) 28
(2, 9) 29
(3, 0) 30
(3, 1) 31
(3, 2) 32
(3, 3) 33
(3, 4) 34
(3, 5) 35
(3, 6) 36
(3, 7) 37
(3, 8) 38
(3, 9) 39
(4, 0) 40
(4, 1) 41
(4, 2) 42
(4, 3) 43
(4, 4) 44
(4, 5) 45
(4, 6) 46
(4, 7) 47
(4, 8) 48
(4, 9) 49
(5, 0) 50
(5, 1) 51
(5, 2) 52
(5, 3) 53
(5, 4) 54
(5, 5) 55
(5, 6) 56
(5, 7) 57
(5, 8) 58
(5, 9) 59
(6, 0) 60
(6, 1) 61
(6, 2) 62
(6, 3) 63
(6, 4) 64
(6, 5) 65
(6, 6) 66
(6, 7) 67
(6, 8) 68
(6, 9) 69
(7, 0) 70
(7, 1) 71
(7, 2) 72
(7, 3) 73
(7, 4) 74
(7, 5) 75
(7, 6) 76
(7, 7) 77
(7, 8) 78
(7, 9) 79
(8, 0) 80
(8, 1) 81
(8, 2) 82
(8, 3) 83
(8, 4) 84
(8, 5) 85
(8, 6) 86
(8, 7) 87
(8, 8) 88
(8, 9) 89
(9, 0) 90
(9, 1) 91
(9, 2) 92
(9, 3) 93
(9, 4) 94
(9, 5) 95
(9, 6) 96
(9, 7) 97
(9, 8) 98
(9, 9) 99
(0, 0) 0
(

In [230]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)

X, Y = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,4))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
Y

array([[-1.        , -1.        , -1.        , -1.        ],
       [-0.33333333, -0.33333333, -0.33333333, -0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333,  0.33333333],
       [ 1.        ,  1.        ,  1.        ,  1.        ]])

In [251]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)

matrix = np.zeros((10,10))
p = 5

#rando = np.random.choice(matrix.shape[0] * matrix.shape[1], p, replace=False)
#x, y = np.unravel_index(rando, matrix.shape)
#matrix[x,y] = 421
#matrix

np.put(matrix,np.random.choice(100, p, replace=False), 111)
matrix

array([[  0.,   0.,   0., 111.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 111.,   0.,   0.,   0., 111.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 111.,   0.,   0.,   0.,   0.,   0.,   0.],
       [111.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [ ]:
#### 58. Subtract the mean of each row of a matrix (★★☆)

arr = np.arange(1,10).reshape(3,3)
arr - arr.mean(axis=1, keepdims=True)


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [271]:
#### 59. How to sort an array by the nth column? (★★☆)
arr = np.random.uniform(1,10, (3,3))
arr[arr[:,1].argsort()]


array([[4.33593751, 1.58367723, 4.481821  ],
       [8.14446975, 8.88459621, 5.10660284],
       [2.8815273 , 9.59494522, 5.44714204]])

In [285]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)
arr = np.array([0,1,2,np.nan,np.nan,np.nan,3,2,1]).reshape(3,3).T
any(np.isnan(arr).all(axis=0))

True

In [291]:
#### 61. Find the nearest value from a given value in an array (★★☆)
arr = np.arange(0,9).reshape(3,3)
value = 50
arr.flat[abs(arr-value).argmin()]

np.int64(8)

In [ ]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
a = np.array([1,2,3])
b = np.array([4,5,6]).T
sum = 0
for index_a, index_b in np.nditer([a,b]):
    sum += index_a + index_b
sum

np.int64(21)

In [316]:
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
a = np.array([1,2,3,4,5])
idx = np.array([0,2,2,2])
np.add.at(a,idx,1)
a

array([2, 2, 6, 4, 5])

In [317]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [331]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
h,w = 50, 50
image = np.random.randint(0,4, (h,w,3)).astype(np.ubyte)
col = np.unique(image.reshape(-1,3), axis=0)
len(col)


64

In [ ]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
arr = np.arange(0,16).reshape(2,2,2,2)
arr.sum(axis=(-1,-2))

array([[ 6, 22],
       [38, 54]])

In [352]:
#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
d = np.arange(10)
i = np.random.randint(0,2,10)
np.bincount(i,d)/np.bincount(i)

array([4.83333333, 4.        ])

In [ ]:
#### 69. How to get the diagonal of a dot product? (★★★)
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)
np.diag(a@b)



array([ 15,  54, 111])

In [363]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
vect = np.array([1, 2, 3, 4, 5])
res = np.zeros(5 + 3*4)
res[::4] = vect
res

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

In [370]:
#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)
a = np.arange(75).reshape(5,5,3)
b = np.arange(25).reshape(5,5)
a*b[:,:,None]

array([[[   0,    0,    0],
        [   3,    4,    5],
        [  12,   14,   16],
        [  27,   30,   33],
        [  48,   52,   56]],

       [[  75,   80,   85],
        [ 108,  114,  120],
        [ 147,  154,  161],
        [ 192,  200,  208],
        [ 243,  252,  261]],

       [[ 300,  310,  320],
        [ 363,  374,  385],
        [ 432,  444,  456],
        [ 507,  520,  533],
        [ 588,  602,  616]],

       [[ 675,  690,  705],
        [ 768,  784,  800],
        [ 867,  884,  901],
        [ 972,  990, 1008],
        [1083, 1102, 1121]],

       [[1200, 1220, 1240],
        [1323, 1344, 1365],
        [1452, 1474, 1496],
        [1587, 1610, 1633],
        [1728, 1752, 1776]]])

In [374]:
#### 72. How to swap two rows of an array? (★★★)
a = np.arange(10).reshape(5,2)
#a[1,:], a[4,:] = a[4,:], a[1,:]
a[[1,4]] = a[[4,1]]
a

array([[0, 1],
       [8, 9],
       [4, 5],
       [6, 7],
       [2, 3]])

In [ ]:
#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
#a = np.array([0,0,1,2,3,4,4])
c = np.bincount(a)
n = np.arange(len(c))
n.repeat(c)

array([0, 0, 1, 2, 3, 4, 4])

In [395]:
#### 75. How to compute averages using a sliding window over an array? (★★★)
#[1,2,3,4,5,6,7,8]  n = 3
def slide(a, n):
    cum_sum = np.cumsum(a,dtype=np.float32)
    cum_sum[n:] = cum_sum[n:] - cum_sum[:-n]
    cum_sum = cum_sum[n-1:] / n
    return cum_sum
slide(np.arange(20), 3)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.], dtype=float32)

In [414]:
#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
np.random.seed(21)
z = np.array([1.0])
np.negative(z, out=z)

boolean = np.random.randint(0,2,100).astype(np.bool)
np.logical_not(boolean, out=boolean)

print(z,boolean)

[-1.] [False False  True  True  True  True  True False  True  True False False
  True  True  True False  True False False False False  True  True  True
  True  True  True  True False  True False  True  True False False  True
 False  True  True  True  True  True  True  True False False  True  True
 False  True  True False False  True  True  True False  True  True  True
  True False  True False  True False False False False  True False  True
  True  True  True  True  True False  True  True  True  True  True  True
 False False False False  True  True False False False  True  True  True
 False  True  True False]


# LAST TWENTY

In [432]:
#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

def generation(Z, n):
    result = []
    for i in range(len(Z) - length + 1):
        result.append(Z[i:i+n])
    return result
generation(np.arange(1,15),4)

# second way
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(1,15)
sliding_window_view(Z, 4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

In [421]:
#### 82. Compute a matrix rank (★★★)
matrix = np.arange(9).reshape(3,3)
np.linalg.matrix_rank(matrix)

np.int64(2)

In [424]:
#### 83. How to find the most frequent value in an array?
a = np.array([1,1,2,3,4,5,5,5,5,5,6,6,100])
np.argmax(np.bincount(a))

np.int64(5)

In [ ]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
from numpy.lib.stride_tricks import sliding_window_view
matrix = np.arange(100).reshape(10,10)
sliding_window_view(matrix, window_shape=(3,3))


array([[[[ 0,  1,  2],
         [10, 11, 12],
         [20, 21, 22]],

        [[ 1,  2,  3],
         [11, 12, 13],
         [21, 22, 23]],

        [[ 2,  3,  4],
         [12, 13, 14],
         [22, 23, 24]],

        [[ 3,  4,  5],
         [13, 14, 15],
         [23, 24, 25]],

        [[ 4,  5,  6],
         [14, 15, 16],
         [24, 25, 26]],

        [[ 5,  6,  7],
         [15, 16, 17],
         [25, 26, 27]],

        [[ 6,  7,  8],
         [16, 17, 18],
         [26, 27, 28]],

        [[ 7,  8,  9],
         [17, 18, 19],
         [27, 28, 29]]],


       [[[10, 11, 12],
         [20, 21, 22],
         [30, 31, 32]],

        [[11, 12, 13],
         [21, 22, 23],
         [31, 32, 33]],

        [[12, 13, 14],
         [22, 23, 24],
         [32, 33, 34]],

        [[13, 14, 15],
         [23, 24, 25],
         [33, 34, 35]],

        [[14, 15, 16],
         [24, 25, 26],
         [34, 35, 36]],

        [[15, 16, 17],
         [25, 26, 27],
         [35, 36, 37]],

    

In [442]:
#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

class Symetric_array(np.ndarray):

    def __setitem__(self, index, value):
        row, col = index 
        super(Symetric_array, self).__setitem__((row,col), value)
        super(Symetric_array, self).__setitem__((col,row), value)

# creating some symetric matrix
matrix = np.arange(9).reshape(3,3)
matrix = ((matrix + matrix.T) / 2).view(Symetric_array)
matrix

#tests 
matrix[1,0] = 3
matrix

matrix[2,2] = -7
matrix

Symetric_array([[ 0.,  3.,  4.],
                [ 3.,  4.,  6.],
                [ 4.,  6., -7.]])

In [448]:
#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

# matrix_1 * vector_1  + ... + matrix_p * vetor_p    <- (n,1) shape
p = 10
n = 5

matrices = np.ones((p,n,n))
vactor = np.ones((p,n,1))
np.tensordot(matrices,vactor, axes = [[0,2],[0,1]]) # we specify which of the dimension we want to use. 0,0 <- we match matrix_i with vector_i, then we multiply matrix*vecotr

array([[50.],
       [50.],
       [50.],
       [50.],
       [50.]])

In [ ]:
#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
matrix = np.arange(256).reshape(16,16)
from numpy.lib.stride_tricks import sliding_window_view
(sliding_window_view(matrix, window_shape=(4,4))).sum(axis=(-2,-1)) #overlapping
sliding_window_view(matrix, windosw_shape=(4,4))[::4,::4].sum(axis=(-2,-1)) #non-overlapping

array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

In [ ]:
#### 88. How to implement the Game of Life using numpy arrays? (★★★)


In [488]:
#### 89. How to get the n largest values of an array (★★★)
arr = np.array([1,2,32,20,11,100,2,3232,1])
n = 3
arr[arr.argsort()[-n:]]
arr[np.argpartition(arr, -n)[-n:]]

array([  32, 3232,  100])

In [ ]:
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

vectors = [np.array([1,2,3]), np.array([4,5,6]), np.array([8,6])]

indexes = np.indices((3,3,2)).reshape(len(vectors), -1).T

for i in range(len(vectors)):
    indexes[:, i] = vectors[i][indexes[:, i]]
indexes

array([[1, 4, 8],
       [1, 4, 6],
       [1, 5, 8],
       [1, 5, 6],
       [1, 6, 8],
       [1, 6, 6],
       [2, 4, 8],
       [2, 4, 6],
       [2, 5, 8],
       [2, 5, 6],
       [2, 6, 8],
       [2, 6, 6],
       [3, 4, 8],
       [3, 4, 6],
       [3, 5, 8],
       [3, 5, 6],
       [3, 6, 8],
       [3, 6, 6]])

In [528]:
#### 91. How to create a record array from a regular array? (★★★)

regular_array = np.array([["john", 181, 23], ["mark", 192, 53]])
record_array = np.core.records.fromarrays(regular_array.T, names='name, height, age')
record_array["age"]
record_array.age

/var/folders/2j/d48_9w_51rgdd433w9hnj70m0000gn/T/ipykernel_2004/2921995022.py:4: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  record_array = np.core.records.fromarrays(regular_array.T, names='name, height, age')


array(['23', '53'], dtype='<U21')

In [536]:
#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

z = np.arange(100)
np.power(z,3)
z**3
np.einsum('i,i,i->i',z,z,z)

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649, 125000, 132651, 140608, 148877, 157464, 166375,
       175616, 185193, 195112, 205379, 216000, 226981, 238328, 250047,
       262144, 274625, 287496, 300763, 314432, 328509, 343000, 357911,
       373248, 389017, 405224, 421875, 438976, 456533, 474552, 493039,
       512000, 531441, 551368, 571787, 592704, 614125, 636056, 658503,
       681472, 704969, 729000, 753571, 778688, 804357, 830584, 857375,
       884736, 912673, 941192, 970299])

In [ ]:
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
a = np.arange(24).reshape(8,3)
b = np.arange(4).reshape(2,2)

np.all([np.any(np.isin(a,row), axis=1) for row in b], axis=0)

array([ True, False, False, False, False, False, False, False])

In [562]:
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
matrix = np.arange(30).reshape(10,3)
matrix[[0,1,3]] = [1,1,1]
matrix[[not np.all(row[0] == row) for row in matrix]]

array([[ 6,  7,  8],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [571]:
#### 95. Convert a vector of ints into a matrix binary representation (★★★)
np.unpackbits(np.array([2,1,2,32,12,41], dtype=np.uint8)).reshape(-1,8)

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 1]], dtype=uint8)

In [577]:
#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
matrix = np.arange(100).reshape(10,10)
matrix[6] = np.arange(10)
np.unique(matrix,axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
a = np.arange(3) #[0,1,2]
b = np.arange(3) #[0,1,2]
np.einsum("i,i->",a,b) # inner a_i * b_i
np.einsum('i,i->i',a,b) #mul
np.einsum('i,j->ij',a,b) #outer
np.einsum('i->',a) #sum

np.int64(3)

In [602]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
x = np.array([0,3,3])
y = np.array([0,0,1])

dist = np.cumsum(np.sqrt(np.diff(x)**2 + np.diff(y)**2))
dist = np.insert(dist, 0, 0)
equidistant = np.linspace(0,dist[-1],len(x)+1)
new_x = np.interp(equidistant, dist,x) 
new_y = np.interp(equidistant, dist, y)
new_x, new_y

(array([0.        , 1.33333333, 2.66666667, 3.        ]),
 array([0., 0., 0., 1.]))

In [ ]:
#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


In [ ]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
